Mvc_Odev/Controllers/DatabaseController.cs
using DataAccess.Contexts;
using DataAccess.Entities;
using DataAccess.Entities.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Text;

namespace Mvc_Odev.Controllers
{
    //public void ObsoleteTest()
    //{
    //    Seed();
    //}

    //[NonAction] // aksiyonun web uygulaması üzerinden çağırılmasını engeller
    //[Obsolete("Bu method artık kullanılmamaktadır!")]
    public class DatabaseController : Controller
    {
        public IActionResult Seed()
        {
            using (KitapContext db = new KitapContext())
            {
                var kitapKitapciEntity = db.KitapKitapcilar.ToList();
                db.KitapKitapcilar.RemoveRange(kitapKitapciEntity);

                var kitapcilarEntity = db.Kitapcilar.ToList();
                db.Kitapcilar.RemoveRange(kitapcilarEntity);

                var kitaplarEntity = db.Kitaplar.ToList();
                db.Kitaplar.RemoveRange(kitaplarEntity);

                var turlerEntity = db.Turler.ToList();
                db.Turler.RemoveRange(turlerEntity);

                var kullaniciDetayiEntities = db.KullaniciDetaylari.ToList();
                db.KullaniciDetaylari.RemoveRange(kullaniciDetayiEntities);

                var kullaniciEntities = db.Kullanicilar.ToList();
                db.Kullanicilar.RemoveRange(kullaniciEntities);

                var rolEntities = db.Roller.ToList();
                db.Roller.RemoveRange(rolEntities);

                var sehirEntities = db.Sehirler.ToList();
                db.Sehirler.RemoveRange(sehirEntities);

                var ulkeEntities = db.Ulkeler.ToList();
                db.Ulkeler.RemoveRange(ulkeEntities);


                if (turlerEntity.Count > 0)
                {
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Kitaplar', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Turler', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Kitapcilar', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Kullanicilar', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Roller', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Sehirler', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Ulkeler', reseed, 0)");
                    db.Database.ExecuteSqlRaw("dbcc checkident ('Kitapcilar', reseed, 0)");
                }

                db.Turler.Add(new Tur()
                {
                    Adi = "Hikaye",
                    Kitaplar = new List<Kitap>()
                    {
                        new Kitap()
                        {
                            Adi = "AAA",
                            YayımTarihi = new DateTime(2000,2,1),
                            BirimFiyati = 9.5,
                            StokMiktari = 3
                        }
                    }
                });
                db.Turler.Add(new Tur()
                {
                    Adi = "Roman",
                    Kitaplar = new List<Kitap>()
                    {
                        new Kitap()
                        {
                            Adi = "BBB",
                            YayımTarihi = DateTime.Parse("03.04.2005", new CultureInfo("tr-TR")),
                            BirimFiyati = 15.5,
                            StokMiktari = 5
                        }
                    }
                });
               
                db.Ulkeler.Add(new Ulke()
                {
                    Adi = "Türkiye",
                    Sehirler = new List<Sehir>()
                    {
                        new Sehir()
                        {
                            Adi = "Ankara"
                        },
                        new Sehir()
                        {
                            Adi = "İstanbul"
                        },
                        new Sehir()
                        {
                            Adi = "İzmir"
                        }
                    }
                });
                db.Ulkeler.Add(new Ulke()
                {
                    Adi = "Amerika Birleşik Devletleri",
                    Sehirler = new List<Sehir>()
                    {
                        new Sehir()
                        {
                            Adi = "New York"
                        },
                        new Sehir()
                        {
                            Adi = "Los Angeles"
                        }
                    }
                });

                db.SaveChanges();

                db.Kitapcilar.Add(new Kitapci()
                {
                    Adi = "A Kitabevi",
                    SanalMi = true,
                    KitapKitapcilar = new List<KitapKitapci>()
                    {
                        new KitapKitapci()
                        {
                            KitapId = db.Kitaplar.SingleOrDefault(kitap => kitap.Adi == "BBB").Id
                        }
                    }
                });
                db.SaveChanges();

                db.Kitapcilar.Add(new Kitapci()
                {
                    Adi = "B Kitabevi",
                    SanalMi = false,
                    KitapKitapcilar = new List<KitapKitapci>()
                    {
                        new KitapKitapci()
                        {
                            KitapId = db.Kitaplar.SingleOrDefault(kitap => kitap.Adi == "AAA").Id
                        }
                    }
                });
                db.SaveChanges();

                db.Roller.Add(new Rol()
                {
                    Adi = "Admin",
                    Kullanicilar = new List<Kullanici>()
                    {
                        new Kullanici()
                        {
                            KullaniciAdi = "okişi",
                            Sifre = "okişi",
                            AktifMi = true,
                            
                            KullaniciDetayi = new KullaniciDetayi()
                            {
                                Adres = "Denizin ortası",
                                Cinsiyet = Cinsiyet.Erkek,
                                Eposta = "guvercin1@hotmail.com",
                                UlkeId = db.Ulkeler.SingleOrDefault(ulke => ulke.Adi == "Türkiye").Id,
                                SehirId = db.Sehirler.SingleOrDefault(sehir => sehir.Adi == "Ankara").Id
                            }
                        }
                    }
                });
                db.Roller.Add(new Rol()
                {
                    Adi = "Kullanıcı",
                    Kullanicilar = new List<Kullanici>()
                    {
                        new Kullanici()
                        {
                            KullaniciAdi = "şukişi",
                            Sifre = "şukişi",
                            AktifMi = true,
                            KullaniciDetayi = new KullaniciDetayi()
                            {
                                Adres = "Dağın başı",
                                Cinsiyet = Cinsiyet.Erkek,
                                Eposta = "guvercin2@hotmail.com",
                                UlkeId = db.Ulkeler.SingleOrDefault(ulke => ulke.Adi == "Amerika Birleşik Devletleri").Id,
                                SehirId = db.Sehirler.SingleOrDefault(sehir => sehir.Adi == "Los Angeles").Id
                            }
                        }
                    }
                });
                db.SaveChanges();
            }
            return Content("<label style=\"color:red;\"><b>İlk veriler başarıyla oluşturuldu.</b></label>", "text/html", Encoding.UTF8);
        }
    }
}

Mvc_Odev/Controllers/HesaplarController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace Mvc_Odev.Controllers
{
    public class HesaplarController : Controller
    {
        private readonly IHesapService _hesapService;
        private readonly IUlkeService _ulkeService;
        private readonly ISehirService _sehirService;

        public HesaplarController(IHesapService hesapService, IUlkeService ulkeService, ISehirService sehirService)
        {
            _hesapService = hesapService;
            _ulkeService = ulkeService;
            _sehirService = sehirService;
        }

        [HttpGet]
        public IActionResult Giris()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Giris(KullaniciGirisModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _hesapService.Giris(model);
                if (result.IsSuccessful)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, result.Data.KullaniciAdi),
                        new Claim(ClaimTypes.Role, result.Data.RolAdiDisplay)
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Cikis()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult YetkisizIslem()
        {
            return View("Hata", "Bu işlem için yetkiniz bulunmamaktadır!");
        }
        
        [HttpGet]
        public IActionResult Kayit()
        {
            ViewBag.Ulkeler = new SelectList(_ulkeService.Query().ToList(), "Id", "Adi");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Kayit(KullaniciKayitModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _hesapService.Kayit(model);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Giris));
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.Ulkeler = new SelectList(_ulkeService.Query().ToList(), "Id", "Adi", model.UlkeId);

            //var sehirResult = _sehirService.List(model.UlkeId.HasValue ? model.UlkeId.Value : -1);
            var sehirResult = _sehirService.List(model.UlkeId ?? -1);

            ViewBag.Sehirler = new SelectList(sehirResult.Data, "Id", "Adi", model.SehirId);

            return View(model);
        }
    }
}

Mvc_Odev/Controllers/KitapcilarController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mvc_Odev.Controllers
{
    [Authorize]
    public class KitapcilarController : Controller
    {
        private readonly IKitapciService _kitapciService;
        private readonly IKitapService _kitapService;
        public KitapcilarController(IKitapciService kitapciService, IKitapService kitapService)
        {
            _kitapciService = kitapciService;
            _kitapService = kitapService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            List<KitapciModel> list = _kitapciService.Query().ToList();
            return View(list);
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(KitapciModel kitapci)
        {
            if (ModelState.IsValid)
            {
                var result = _kitapciService.Add(kitapci);
                if (result.IsSuccessful)
                {
                    TempData["Mesaj"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(kitapci);
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            KitapciModel model = _kitapciService.Query().SingleOrDefault(kitapci => kitapci.Id == id);
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(KitapciModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _kitapciService.Update(model);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(model);
        }
        
        public IActionResult Details(int? id)
        {
            KitapciModel model = _kitapciService.Query().SingleOrDefault(kitapci => kitapci.Id == id.Value);
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            KitapciModel model = _kitapciService.Query().SingleOrDefault(kitapci => kitapci.Id == id.Value);
            return View(model);
        }
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (!(User.Identity.IsAuthenticated && User.IsInRole("Admin")))
                return RedirectToAction("YetkisizIslem", "Hesaplar");

            var result = _kitapciService.Delete(id.Value);
            if (result.IsSuccessful)
                TempData["Success"] = result.Message;
            else
                TempData["Error"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

Mvc_Odev/Controllers/TurlerController.cs
using AppCore.Business.Models;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mvc_Odev.Controllers
{
    public class TurlerController : Controller
    {
        private readonly ITurService _turService;

        public TurlerController(ITurService turService)
        {
            _turService = turService;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<TurModel> model = _turService.Query().ToList();
            return View(model);
        }
        
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string Adi)
        {
            TurModel model = new TurModel()
            {
                Adi = Adi
            };
            var result = _turService.Add(model);
            if (result.IsSuccessful)
                return RedirectToAction(nameof(Index));
            return View("Hata", result.Message);
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            TurModel model = _turService.Query().SingleOrDefault(tur => tur.Id == id);
            if (model == null)
                return View("Hata", "Tür bulunamadı!");
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TurModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _turService.Update(model);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(model);
        }
        
            [Authorize(Roles = "Admin")]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            TurModel model = _turService.Query().SingleOrDefault(tur => tur.Id == id.Value);
            if (model == null)
                return View("Hata", "Tür bulunamadı!");
            return View(model);
        }
        
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            Result result = _turService.Delete(id.Value);
            TempData["Mesaj"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

Mvc_Odev/Views/Shared/Hata.cshtml
@model string

<h1 class="text-danger">Hata!</h1>

@if (string.IsNullOrWhiteSpace(Model))
{
    <p class="text-danger">İşlem sırasında hata meydana geldi!</p>
}
else
{
    <p class="text-danger">@Model</p>
}

Mvc_Odev/Views/Shared/_Layout.cshtml
@using Mvc_Odev.Settings
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@AppSettings.Baslik | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc_Odev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@AppSettings.Baslik</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Turler" asp-action="Index">Kitap Türleri</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitaplar" asp-action="Index">Kitaplar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitapcilar" asp-action="Index">Kitapcılar</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Database" asp-action="Seed"><b>Verileri Sıfırla</b></a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
        
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a asp-action="Kayit" asp-controller="Hesaplar">Kayıt</a>
                            </li>@:&nbsp &nbsp    
                            <li class="nav-item">
                                <a asp-action="Giris" asp-controller="Hesaplar">Giriş</a>
                            </li>@:&nbsp &nbsp    
                        }
                        else
                        {
                            <li class="nav-item">
                                <label>@User.Identity.Name</label>
                            </li>@:&nbsp &nbsp
                            <li>
                                <a asp-action="Cikis" asp-controller="Hesaplar">Çıkış</a>
                            </li>@:&nbsp &nbsp
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="text-danger" asp-controller="Database" asp-action="Seed"><b>Verileri Sıfırla</b></a>
                            </li>
                        }
                    </ul>  
                </div>
            </div>
        </nav>     
    
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>