Mvc_Odev/Controllers/HesaplarController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace Mvc_Odev.Controllers
{
    public class HesaplarController : Controller
    {
        private readonly IHesapService _hesapService;
        private readonly IUlkeService _ulkeService;
        private readonly ISehirService _sehirService;

        public HesaplarController(IHesapService hesapService, IUlkeService ulkeService, ISehirService sehirService)
        {
            _hesapService = hesapService;
            _ulkeService = ulkeService;
            _sehirService = sehirService;
        }

        [HttpGet]
        public IActionResult Giris()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Giris(KullaniciGirisModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _hesapService.Giris(model);
                if (result.IsSuccessful)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, result.Data.KullaniciAdi),
                        new Claim(ClaimTypes.Role, result.Data.RolAdiDisplay)
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Cikis()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult YetkisizIslem()
        {
            return View("Hata", "Bu işlem için yetkiniz bulunmamaktadır!");
        }
        
        [HttpGet]
        public IActionResult Kayit()
        {
            ViewBag.Ulkeler = new SelectList(_ulkeService.Query().ToList(), "Id", "Adi");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Kayit(KullaniciKayitModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _hesapService.Kayit(model);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Giris));
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.Ulkeler = new SelectList(_ulkeService.Query().ToList(), "Id", "Adi", model.UlkeId);

            //var sehirResult = _sehirService.List(model.UlkeId.HasValue ? model.UlkeId.Value : -1);
            var sehirResult = _sehirService.List(model.UlkeId ?? -1);

            ViewBag.Sehirler = new SelectList(sehirResult.Data, "Id", "Adi", model.SehirId);

            return View(model);
        }
    }
}

Mvc_Odev/Views/Hesaplar/Giris.cshtml
@*@model DataAccess.Entities.Kullanici*@
@model KullaniciGirisModel

@{
    ViewData["Title"] = "Kullanıcı Girişi";
}

<h1>@ViewData["Title"]</h1>

<h4>Kullanıcı</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Giris" asp-controller="Hesaplar" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KullaniciAdi" class="control-label"></label>
                <input asp-for="KullaniciAdi" class="form-control" />
                <span asp-validation-for="KullaniciAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sifre" class="control-label"></label>
                <input asp-for="Sifre" class="form-control" type="password" />
                <span asp-validation-for="Sifre" class="text-danger"></span>
            </div>&nbsp;
            @*<div class="form-group">
                <label asp-for="RolId" class="control-label"></label>
                <select asp-for="RolId" class ="form-control" asp-items="ViewBag.RolId"></select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Giriş" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

Mvc_Odev/Views/Hesaplar/Kayit.cshtml
@*@model DataAccess.Entities.Kullanici*@
@model KullaniciKayitModel
@using DataAccess.Entities.Enums


@{
    ViewData["Title"] = "Kayıt";
}

<h1>@ViewData["Title"]</h1>

<h4>Kullanıcı</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Kayit">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KullaniciAdi" class="control-label"></label>
                <input asp-for="KullaniciAdi" class="form-control" />
                <span asp-validation-for="KullaniciAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sifre" class="control-label"></label>
                <input asp-for="Sifre" class="form-control" type="password" />
                <span asp-validation-for="Sifre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SifreOnay" class="control-label"></label>
                <input asp-for="SifreOnay" class="form-control" type="password" />
                <span asp-validation-for="SifreOnay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Eposta" class="control-label"></label>
                <input asp-for="Eposta" class="form-control" type="email" />
                <span asp-validation-for="Eposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <textarea asp-for="Adres" class="form-control"></textarea>
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cinsiyet" class="control-label"></label>
                <input asp-for="Cinsiyet" type="radio" value="@((int)Cinsiyet.Kadın)" checked/>@Cinsiyet.Kadın
                &nbsp;
                <input asp-for="Cinsiyet" type="radio" value="@((int)Cinsiyet.Erkek)" />@Cinsiyet.Erkek
                <span asp-validation-for="Cinsiyet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UlkeId" class="control-label"></label>
                <div class="col-5">
                    <select asp-for="UlkeId" asp-items="ViewBag.Ulkeler" class="form-control" id="ulkeler">
				        <option value="">-- Seçiniz --</option>
				    </select>
                    <span asp-validation-for="UlkeId" class="text-danger" id="ulkemesaj"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="SehirId" class="control-label"></label>
                <div class="col-5">
                    <select asp-for="SehirId" asp-items="ViewBag.Sehirler" class="form-control sehirler">
				        <option value="">-- Ülke Seçiniz --</option>
				    </select>
                    <span asp-validation-for="SehirId" class="text-danger"></span>
                </div>
            </div>&nbsp;&nbsp;
            
            @*<div class="form-group">
                <label asp-for="RolId" class="control-label"></label>
                <select asp-for="RolId" class ="form-control" asp-items="ViewBag.RolId"></select>
            </div>*@
            
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
                &nbsp;&nbsp;
                <button type="reset" class="btn btn-outline-primary">Temizle</button>
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts 
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @*<partial name="_ValidationScriptsPartial" />*@

<script>
     $(function() {
        $("#ulkeler").change(function() {
            var seciliUlkeId = $("#ulkeler").val();
             $(".sehirler").empty();
            if (seciliUlkeId == "") {
                $("#ulkemesaj").text("Ülke seçiniz...");
                $(".sehirler").append('<option value="">-- Ülke Seçiniz --</option>');
            }
            else {
                $.getJSON(
                    "/Sehirler/SehirlerGet",
                    { ulkeId: seciliUlkeId },
                    function(sehirler) {
                        $(".sehirler").append('<option value="">-- Şehir Seçiniz --</option>');
                        for (var i = 0; i < sehirler.length; i++) {
                            $(".sehirler").append('<option value="' + sehirler[i].id + '">' + sehirler[i].adi + '</option>');
                        }
                    }
                );
            }
        });
     });

    //$.ajax({
    //        type: "post",
    //        url: "/Sehirler/SehirlerPost",
    //        data: { ulkeId: seciliUlkeId },
    //        cache: false,
    //        //contentType: "application/json;charset=utf-8;",
    //        dataType: "json",
    //        success: function(sehirler) {
    //            $(".sehirler").append('<option value="">-- Şehir Seçiniz --</option>');
    //            for (var i = 0; i < sehirler.length; i++) {
    //            $(".sehirler").append('<option value="' + sehirler[i].id + '">' + sehirler[i].adi + '</option>');
    //            }
    //        },
    //        error: function() {
    //            alert("İşlem sırasında hata oldu!");
    //        }
    //});
</script>

}