Mvc_Odev/Controllers/KitaplarController.cs
using Business.Models;
using Business.Models.Filters;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mvc_Odev.Models;

namespace Mvc_Odev.Controllers
{
    [Authorize]
    public class KitaplarController : Controller
    {
        private readonly IKitapService _kitapService;
        private readonly ITurService _turService;
        private readonly IKitapciService _kitapciService;

        public KitaplarController(IKitapService kitapService, ITurService turService, IKitapciService kitapciService)
        {
            _kitapService = kitapService;
            _turService = turService;
            _kitapciService = kitapciService;
        }

        [AllowAnonymous]
        public IActionResult Index(KitapFiltreModel filtre)
        {
            var result = _kitapService.List(filtre);
            KitaplarIndexViewModel viewModel = new KitaplarIndexViewModel()
            {
                Kitaplar = result.Data,
                Turler = new SelectList(_turService.Query().ToList(),"Id","Adi"),
                Filtre = filtre
            };
            //return View(model);
            return View(viewModel);
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["TurId"] = new SelectList(_turService.Query().ToList(), "Id", "Adi");
            ViewBag.Kitapcilar = new MultiSelectList(_kitapciService.Query().ToList(), "Id", "Adi");
            
            KitapModel model = new KitapModel()
            {
                BirimFiyati = 0,
                StokMiktari = 0
            };
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(KitapModel kitap)
        {
            if (ModelState.IsValid)
            {
                var result = _kitapService.Add(kitap);
                if (result.IsSuccessful)
                {
                    TempData["Mesaj"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            ViewData["TurId"] = new SelectList(_turService.Query().ToList(), "Id", "Adi", kitap.TurId);
            ViewBag.Kitapcilar = new MultiSelectList(_kitapciService.Query().ToList(), "Id", "Adi",kitap.KitapciIdleri);
            return View(kitap);
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            KitapModel kitap = _kitapService.Query().SingleOrDefault(kitap => kitap.Id == id);
            if (kitap == null)
                return View("Hata", "Kitap bulunamadı!");
            ViewBag.TurId = new SelectList(_turService.Query().ToList(), "Id", "Adi", kitap.TurId);
            ViewBag.Kitapcilar = new MultiSelectList(_kitapciService.Query().ToList(), "Id", "Adi", kitap.KitapciIdleri);
            return View(kitap);
        }
        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(KitapModel kitap)
        {
            if (ModelState.IsValid)
            {
                var result = _kitapService.Update(kitap);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.TurId = new SelectList(_turService.Query().ToList(), "Id", "Adi", kitap.TurId.Value);
            ViewBag.Kitapcilar = new MultiSelectList(_kitapciService.Query().ToList(), "Id", "Adi", kitap.KitapciIdleri);
            return View(kitap);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Hata");
            }
            KitapModel kitap = _kitapService.Query().SingleOrDefault(kitap => kitap.Id == id.Value);
            if (kitap == null)
            {
                return View("Hata", "Kitap bulunamadı!");
            }
            return View(kitap);
        }
        //[Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (!(User.Identity.IsAuthenticated && User.IsInRole("Admin")))
                return RedirectToAction("YetkisizIslem", "Hesaplar");
            
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            var result = _kitapService.Delete(id.Value);
            if (result.IsSuccessful)
                TempData["Success"] = result.Message;
            else
                TempData["Error"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

Mvc_Odev/Views/Kitaplar/Create.cshtml
@*@model DataAccess.Entities.Kitap*@
@model KitapModel

@{
    ViewData["Title"] = "Ekle";
}

<h1>@ViewData["Title"]</h1>

<h4>Kitap</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Kitaplar" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Adi" class="control-label"></label>
                <input asp-for="Adi" class="form-control" />
                <span asp-validation-for="Adi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aciklamasi" class="control-label"></label>
                <textarea asp-for="Aciklamasi" class="form-control"></textarea>
                <span asp-validation-for="Aciklamasi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YayımTarihi" class="control-label"></label>
                <input asp-for="YayımTarihi" class="form-control" id="tarih" type="text" />
                <span asp-validation-for="YayımTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirimFiyati" class="control-label"></label>
                <input asp-for="BirimFiyati" class="form-control" />
                <span asp-validation-for="BirimFiyati" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StokMiktari" class="control-label"></label>
                <input asp-for="StokMiktari" class="form-control" />
                <span asp-validation-for="StokMiktari" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurId" class="control-label"></label>
                <select asp-for="TurId" class ="form-control" asp-items="ViewBag.TurId">
                <option value="">-- Seçiniz --</option>
                </select>&nbsp
            </div>
            <div class="form-group">
                <label asp-for="KitapciIdleri" class="control-label"></label>
                <select multiple asp-for="KitapciIdleri" class ="form-control" asp-items="ViewBag.Kitapcilar">
                @*<option value="">-- Seçiniz --</option>*@
                </select>&nbsp
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

@section Scripts
{
	<partial name="_ValidationScriptsPartial" />

	<link href="/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
    <script src="/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.tr.min.js"></script>

	<script>
		$(function(){
			$('#tarih').datepicker({
				todayBtn: "linked",
				clearBtn: true,
				language: "tr",
				orientation: "top auto",
				autoclose: true,
				todayHighlight: true
			});
		});
	</script>
}

Mvc_Odev/Views/Kitaplar/Details.cshtml
@*@model DataAccess.Entities.Kitap*@
@model KitapModel

@{
    ViewData["Title"] = "Detay";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Kitap</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aciklamasi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aciklamasi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YayımTarihi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YayımTarihi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirimFiyati)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirimFiyati)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TurAdiDisplay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TurAdiDisplay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KitapciAdlariDisplay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KitapciAdlariDisplay)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Düzenle</a> |
    <a asp-action="Index">Listeye Dön</a>
</div>

Mvc_Odev/Views/Kitaplar/Edit.cshtml
@*@model DataAccess.Entities.Kitap*@
@model KitapModel

@{
    ViewData["Title"] = "Düzenle";
}

<h1>@ViewData["Title"]</h1>

<h4>Kitap</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Kitaplar" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Adi" class="control-label"></label>
                <input asp-for="Adi" class="form-control" />
                <span asp-validation-for="Adi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aciklamasi" class="control-label"></label>
                <textarea asp-for="Aciklamasi" class="form-control"></textarea>
                <span asp-validation-for="Aciklamasi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YayımTarihi" class="control-label"></label>
                <input asp-for="YayımTarihi" class="form-control" id="tarih" type="text" />
                <span asp-validation-for="YayımTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirimFiyati" class="control-label"></label>
                <input asp-for="BirimFiyati" class="form-control" />
                <span asp-validation-for="BirimFiyati" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StokMiktari" class="control-label"></label>
                <input asp-for="StokMiktari" class="form-control" />
                <span asp-validation-for="StokMiktari" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurId" class="control-label"></label>
                <select asp-for="TurId" class="form-control" asp-items="ViewBag.TurId"></select>&nbsp
                <span asp-validation-for="TurId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KitapciIdleri" class="control-label"></label>
                <select asp-for="KitapciIdleri" class="form-control" asp-items="ViewBag.Kitapcilar"></select>&nbsp
                <span asp-validation-for="KitapciIdleri" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
          
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

@section Scripts
{
	<partial name="_ValidationScriptsPartial" />

	<link href="/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
    <script src="/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.tr.min.js"></script>

	<script>
		$(function(){
			$('#tarih').datepicker({
				todayBtn: "linked",
				clearBtn: true,
				language: "tr",
				orientation: "top auto",
				autoclose: true,
				todayHighlight: true
			});
		});
	</script>
}

Mvc_Odev/Views/Kitaplar/Index.cshtml
@*@model IEnumerable<DataAccess.Entities.Kitap>*@
@*@model IEnumerable<KitapModel>*@
@model KitaplarIndexViewModel

@{
    ViewData["Title"] = "Kitaplar";
}

<h1>@ViewData["Title"]</h1>

@if (TempData["Mesaj"] != null)
{
    <p class="bg-success text-white">
        @TempData["Mesaj"]
    </p>
}

@if (TempData["Success"] != null)
{
    <p class="text-success">@TempData["Success"]</p>
}
@if (TempData["Error"] != null)
{
    <p class="text-danger">@TempData["Error"]</p>
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Kitap ekle</a>
    </p>
}


<form asp-action="Index" method="get"> 
    <div class="row" style="padding-bottom: 30px; padding-top: 30px;">
        <div class="col-1">
            <label asp-for="Filtre.KitapAdi"></label>
        </div>
        <div class="col-3">
            <input asp-for="Filtre.KitapAdi" class="form-control" />
        </div>
        <div class="col-1">
            <label asp-for="Filtre.TurId"></label>
        </div>
        <div class="col-3">
            <select asp-for="Filtre.TurId" class="form-control" asp-items="@Model.Turler">
                <option value="">--Tümü--</option>
            </select> 
        </div>
        <div class="col-1">
            <label asp-for="Filtre.BirimFiyatiBaslangic"></label>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input asp-for="Filtre.BirimFiyatiBaslangic" class="form-control" />
                <span class="input-group-text">-</span>
                <input asp-for="Filtre.BirimFiyatiBitis" class="form-control" />
            </div>
        </div>
        <div>
            <br />
        </div>
        <div class="col-1">
            <label asp-for="Filtre.StokMiktariBaslangic"></label>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input asp-for="Filtre.StokMiktariBaslangic" class="form-control" />
                <span class="input-group-text">-</span>
                <input asp-for="Filtre.StokMiktariBitis" class="form-control" />
            </div>
        </div>
        <div class="col-1">
            <label asp-for="Filtre.YayımTarihiBaslangic"></label>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input asp-for="Filtre.YayımTarihiBaslangic" class="form-control" type="date"  />
                <span class="input-group-text">-</span>
                <input asp-for="Filtre.YayımTarihiBitis" class="form-control" type="date"  />
            </div>
        </div>
    </div>
    <div class="row" style="padding-bottom: 30px;">
        <div class="col-12"> 
            <input type="submit" value="Ara" class="btn btn-primary" />
		    &nbsp;&nbsp;
            <a asp-action="Index" class="btn btn-outline-primary">Temizle</a>
        </div>
    </div>
</form>


@if (Model.Kitaplar != null && Model.Kitaplar.Count > 0)
{
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().Adi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().TurAdiDisplay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().Aciklamasi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().YayımTarihiDisplay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().BirimFiyatiDisplay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().StokMiktari)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kitaplar.FirstOrDefault().KitapciAdlariDisplay)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Kitaplar) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Adi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TurAdiDisplay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aciklamasi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YayımTarihiDisplay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirimFiyatiDisplay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StokMiktari)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KitapciAdlariDisplay)
            </td>
            <td>
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-action="Details" asp-route-id="@item.Id">Detay</a>@:&nbsp; &nbsp;
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a><text>&nbsp; &nbsp;</text>
                        <a asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                    }
                }
            </td>
        </tr>
}
    </tbody>
</table>
}
else
{
    <p class="text-danger">Kitap bulunamadı</p>
}